### ISSUE TITLE
Can't find any working documentation

### ISSUE THREAD

**Issue by vladfaust** [aevernon/commission_junction#7]
CJ's web sites / services are piece of sh*t. Waste of code. Slow as f*ck.

I can't access any documentation. It keeps redirecting me to member login page even if I have successfully logged in before. Salesforce support keeps doing that too.

What's wrong with these guys?

**Comment by aevernon** [comment]
Are you able to log into https://cjcommunity.force.com/s/article/4777058 ?

Make sure you have disabled your ad blocker extensions such as Privacy Badger, uBlock Origin, and Adblock Plus.

**Comment by vladfaust** [comment]
I've cleary disabled all ad blockers and no, it keeps redirecting :cry:

**Comment by aevernon** [comment]
I'm sorry, but I don't have a solution to this problem. Can you open a support ticket with CJ?

**Comment by vladfaust** [comment]
@aevernon you see the irony - I cannot even access CJ support :smile:

Nevertheless, these guys just do care so do I. One affiliate means nothing to them.

**Comment by aevernon** [comment]
Looks like the documentation is publicly available again.

https://developers.cj.com/docs/rest-apis/overview
